### ISSUE TITLE
Score sorting

### ISSUE THREAD

**Issue by Therzok** [dfilimon/Jeopy#23]
Score is being sorted alphabetically, not by integer.

**Comment by dfilimon** [comment]
Yes, I remember that was an issue :)
Thank you. And wow, somebody plans on using this...? After so long... :)

:+1:

**Comment by Therzok** [comment]
It's been used for USO's last lab annually from what I've heard. :P

**Comment by dfilimon** [comment]
So that's still the case. Glad to hear it. That was its initial purpose. :)

**Comment by Therzok** [comment]
Also, mind if I run some regex to empty lines with just spaces/tabs? Won't go into replacing all spaces with tabs or all tabs with spaces, since it might screw up some stuff. :p

**Comment by Therzok** [comment]
Also, can you use print("bla") in Python 2.x? Python 3.0 made it a function, no longer usable without parantheses. I can also fix that. ;P

**Comment by Therzok** [comment]
Addition to https://github.com/dfilimon/Jeopy/issues/23#issuecomment-12090792 : Also fixing indentation.

**Comment by dfilimon** [comment]
So:
1. indentation/spaces: sure, have fun with that; s/\s*$// your heart out :)
2. about print() and Python 2.x... yes, but only in more recent versions of Python or something. I only ever used Python 2.6+ so that worked fine.

I remember looking into whether I could use Python 3, but the problem at the time was that Python 3 version of Pyro was still in development.
It would be nice to migrate everything to Python 3 but I have no interest in doing that any time soon. Feel free to play around with it if you want. :)

**Comment by dfilimon** [comment]
Oh and, please make separate patches for these issues.
As in the sorting fix is one patch, the indentation fix is a different patch.

**Comment by Therzok** [comment]
It's still Python 2.0. It just is a compatibility fix to import from **future** versions of Python. That doesn't mean you have to update to Python 3.0.

And the patch is committed in Issue #26 . Didn't split because of Fork limitations to commit addition.

And I didn't commit the sorting fix since it seems to be a PyQt4 thing.

**Comment by Therzok** [comment]
I found a way to set a custom sorting model, can you please point me to where the column for score is set? I need to create a new Widget based on QTableWidgetItem which uses a custom sort model. ;D

**Comment by dfilimon** [comment]
So this [1] is where the sorting happens.

[1] https://github.com/dfilimon/Jeopy/blob/cdl/PlayerTableWidget.py#L89

**Comment by Therzok** [comment]
Yeah, I need to remake the Widget and set a custom sort model to it. I'll handle it.

**Comment by Therzok** [comment]
So to understand it perfectly, column: len(player) - 1 is the score column. ;D I'm going to fix it later tonight.
