### ISSUE TITLE
Code is messy.

### ISSUE THREAD

**Issue by Therzok** [dfilimon/Jeopy#25]
Code is messy, needs fixup to indentation.
3.0 compatibility.

**Comment by dfilimon** [comment]
Therzok, is this still an issue? Do you plan to fix more stuff?

**Comment by Therzok** [comment]
Still some inconsistencies in usage or lack of parantheses and so on. But I'm not going to clean that up yet. I'll make a new Issue when I'm going to start working on constant coding style. =D
