### ISSUE TITLE
User can ask multiple questions and skip them

### ISSUE THREAD

**Issue by mihaimaruseac** [dfilimon/Jeopy#27]
Have user click on all available buttons for question selection. Then have the server select one of them. All of the other ones are lost.

**Comment by dfilimon** [comment]
Wait, how does a user click on all of the available buttons in the grid again? :)

**Comment by mihaimaruseac** [comment]
Tested with @alexandrujuncu today. He answered OK one question and tried to chose another. He clicked all the available questions (300, 400 and 500 in the same category) and the server received all three events. Nothing bad here.

Except that after dismissing those popups and answering the latest question (each popup dismissal changed the question) all the clicked buttons were disabled: all questions were asked even though a single one was intended.

**Comment by dfilimon** [comment]
Oh okay, I get what you're saying. Yep, indeed an issue.

**Comment by mihaimaruseac** [comment]
Seems no more work is being done so I'll just close it
